---
- name: Configure EC2 instance
  hosts: all
  become: yes
  tasks:
    - name: Update and upgrade yum packages
      yum:
        name: '*'
        state: latest

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Install pip
      yum:
        name: python3-pip
        state: present

    - name: Install Docker Compose
      pip:
        name: docker-compose
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
