---
- name: Configure EC2 instance
  hosts: all
  become: yes
  tasks:
    - name: Get Controlled Node Distribution
      ansible.builtin.debug:
        msg: "{{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Add new user
      ansible.builtin.user:
        name: web
        password: 
        state: present
        shell: /bin/bash
        system: no

    - name: Install Apache
      ansible.builtin.yum:
        name: httpd
        state: installed

    - name: Enable and start httpd service
      ansible.builtin.service:
        name: httpd
        enabled: yes
        state: started

    - name: Install PHP
      ansible.builtin.yum:
        name: 
          - php
          - php-mysql
        state: latest

    - name: Install Docker
      ansible.builtin.yum:
        name: docker
        state: present

    - name: Install pip
      ansible.builtin.yum:
        name: python3-pip
        state: present

    - name: Install Docker Compose
      ansible.builtin.pip:
        name: docker-compose
        state: present

    - name: Start and enable Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes
