---
- name: Configure EC2 instance
  hosts: all
  become: yes
  tasks:
    - name: Get Controlled Node Distribution
      ansible.builtin.debug:
        msg: "{{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Add new user
      ansible.builtin.user:
        name: web
        password: 
        state: present
        shell: /bin/bash
        system: no

    - name: Install Apache
      ansible.builtin.command:
        cmd: yum install -y httpd

    - name: Enable and start httpd service
      ansible.builtin.service:
        name: httpd
        enabled: yes
        state: started

    - name: Install PHP
      ansible.builtin.command:
        cmd: yum install -y php php-mysql

    - name: Install Docker
      ansible.builtin.command:
        cmd: yum install -y docker

    - name: Install pip
      ansible.builtin.command:
        cmd: yum install -y python3-pip

    - name: Install Docker Compose
      ansible.builtin.pip:
        name: docker-compose
        state: present

    - name: Downgrade urllib3 to a compatible version
      ansible.builtin.pip:
        name: urllib3==1.26.15
        state: present

    - name: Start and enable Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to the docker group
      ansible.builtin.user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Copy Docker Compose file
      ansible.builtin.copy:
        src: docker-compose.yml
        dest: /home/ec2-user/docker-compose.yml
        owner: ec2-user
        group: ec2-user
        mode: '0644'

    - name: Verify Docker installation
      ansible.builtin.shell:
        cmd: sudo docker --version

    - name: Verify Docker Compose installation
      ansible.builtin.shell:
        cmd: sudo /usr/local/bin/docker-compose --version

    - name: Run Docker Compose
      ansible.builtin.shell:
        cmd: sudo /usr/local/bin/docker-compose up -d
        chdir: /home/ec2-user
